### ISSUE TITLE
I've only ever done Jekyll step by step

### ISSUE THREAD

**Issue by DizzyDez** [DizzyDez/portfolio-designs#1]
so in order to make just the header in jekyll would have to delete all the boilerplate from my index? and put into defaults? I'm not sure how to jekyll-ify with a website that is already finished.
@MB3Online

**Comment by ericadamski** [comment]
It sounds like you have it right. I will be marking the assignments this weekend so you can just hand in your url and continue to work on it.

Just make sure that it isn't broken by Friday :p

**Comment by DizzyDez** [comment]
I need someone to look at my code and see what I'm doing wrong, I have done all the steps to the t, and it's not showing in my code. @CelesteLavo0118

**Comment by ericadamski** [comment]
@DizzyDez I suggest you get someone like @ashtastic (if she has time 😉 ) or anyone else from class to look over it for you.
