### ISSUE TITLE
404

### ISSUE THREAD

**Issue by DizzyDez** [DizzyDez/portfolio-designs#3]
I have designed and styled my 404 page, following the steps on learn-the-web, including adding an .htaccess file. None of my styling is active on the 404 page, neither is the rest of the default layout. 
@ericadamski
@thomasjbradley

**Comment by ericadamski** [comment]
You might want to use the default layout in your yaml front matter?
```
---
layout: ...? 🍦
permalink: 404.html
---
```

**Comment by DizzyDez** [comment]
That did it, thanks Eric!
@ericadamski
