### ISSUE TITLE
Having issues with bring it up on my own domain

### ISSUE THREAD

**Issue by DizzyDez** [DizzyDez/portfolio-designs#4]
I have my website looking great here, might need a better resolution photo... but it doesn't seem to want to work on my own domain. it works great as localhost:4000, but as soon as I go to my domain all the styling goes away. 
please help?
@thomasjbradley
@ericadamski

**Comment by ericadamski** [comment]
this line https://github.com/DizzyDez/portfolio-designs/blob/gh-pages/_config.yml#L2 should be `https://dizzydez.github.io/portfolio-designs`

**Comment by DizzyDez** [comment]
Perfect! Thanks Eric!
