### ISSUE TITLE
Cloudflare just informed me my website is no longer online

### ISSUE THREAD

**Issue by DizzyDez** [DizzyDez/portfolio-designs#5]
Hey guys! 
I know I am no longer in either of your classes, but I was hoping to continue my website after graduation. 
<img width="804" alt="screen shot 2017-10-09 at 5 58 26 pm" src="https://user-images.githubusercontent.com/10464601/31360266-866183b0-ad1b-11e7-83c9-96a5d12fc99f.png">
Problem is I'm not sure which Registrars account I used when building this site. And I can't find the assignment that we used to create this. Any ideas?

Thanks in advance.
@thomasjbradley
@MB3Online

**Comment by thomasjbradley** [comment]
The registrar would have been [Hover.com](https://www.hover.com)—check in there and see if it's hooked up.

Here's the tutorial from before to help you determine if your domain points to CloudFlare:
https://learn-the-web.algonquindesign.ca/courses/web-dev-5/hosting-setup/#step-2

**Comment by DizzyDez** [comment]
Thanks Thomas!
I knew it was something like that, just wasn't sure which site we used! I renewed my domain with hover. I guess it will be back online soon.
